server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: dev

  thymeleaf:
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  aop:
    proxy-target-class: true

    # 最大支持文件大小
  servlet:
    multipart:
      max-file-size: 100MB
    # 最大支持请求大小
      max-request-size: 100MB
      #默认支持文件上传
      enabled: true
      #支持文件写入磁盘.
      file-size-threshold: 0
      # 上传文件的临时目录
      location:

mybatis-plus:
  # 实体类扫描路径
  type-aliases-package: com.aoke.apartmentsystem.system.entity,com.aoke.apartmentsystem.generator.entity,com.aoke.apartmentsystem.job.entity
  # xml 扫描路径
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false